# Numpy A-Z You Need To Do Data Anaysis

In [ ]:
#With notes

**NOTE**

To create array: np.array()


To check type: type(function name)

To check dimention: Array_Nam.ndim

Indexing: Array_Nam[0]

2D:Array_Nam[0,1] #2nd element on 1st row

Slicing:Array_Nam[0:5]

Shape:Array_Nam.shape

Data Type: Array_Name.dtype

To change data type: astype()

To chabge a element:x=Array_Nam.copy
Array_Name[0]=1/anything

To iterating(go through each element): for loop / nditer

To join: concatenate/stack

To join along with rows: concatenate/stack(axis=1)

To split=Array_Name_split

**Random**

To generate 100 random numbers: random.rand(100)

To generate 0-100 a numbers: random.randint(100)

To generate a random array: random.randint(100, size=5/6)


**Universal Function**

To add:np.add


To Build you universal function:
 np.frompyfunc(Function_Name,2,1)

To remove decimal places:trunc()/fix()

Round off 3.1666 to 2 decimal places:np.around(3.1666, 2)

To round off nearest upper integer=Ceil


In [ ]:
import numpy as np

# **NumPy Creating Arrays**

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

**Check Number of Dimensions?**

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


#Checking dimentions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
#Which means[] using this you can have dimentions

0
1
2
3


Create an array with 5 dimensions and verify that it has 5 dimensions:

In [ ]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("number of dimentions:",arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimentions: 5


# NumPy Array Indexing

For an example get the first element of the array

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])


1


add the first and second element

In [ ]:
print(arr[0]+arr[1])

3


How to access 2D data

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


# For 3D array:
The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


# NumPy Array Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


STEP

Use the step value to determine the step of the slicing:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# Data Types

**i - integer**
**b - boolean**
u - unsigned integer
**f - float**
**c - complex float**
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
arr=np.random.rand(10)
print(arr.dtype)
print(arr)

float64
[0.03771194 0.654792   0.33108321 0.57861765 0.00659381 0.55139994
 0.54038996 0.57467799 0.62521032 0.33523993]


In [ ]:
arr=np.array([1,2,2,2,2,4],dtype="S")

print(arr.dtype)
print(arr)

|S1
[b'1' b'2' b'2' b'2' b'2' b'4']


# Converting Data Type on Existing Arrays

In [ ]:
arr=np.array([1.1,2.1,3.1])

newarr=arr.astype("i")

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
arr=np.array([1.1,2.1,3.1])

newarr=arr.astype("bool")

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


# NumPy Array Copy vs View

In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=23
print(arr)
print(x)

[23  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of array

In [ ]:
arr.shape

(5,)

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# Reshaping arrays

1D to 2D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
#first digit is collum second digit is row

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
newarr = arr.reshape(2, 3,2)
#first one is array second one is collum and the third one is row
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

**reshape(-1)**

In [ ]:
arr = np.array([[1, 2, 4], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 4 4 5 6]


# NumPy Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
arr=np.array([1,2,3])
for x in arr:
  print(x)

1
2
3


In a 2-D array it will go through all the rows.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


Iterate on each scalar element of the 2-D array:

In [ ]:
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#a 3D array

In [ ]:
for x in arr1:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
for x in arr1:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
for x in np.nditer(arr[:, ::2]):
  print(x)


1
2
5
6


# Joining Array



In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
aa=np.concatenate((arr1,arr2))
aa

array([1, 2, 3, 4, 5, 6])

In [ ]:
#joining 2D array along with rows(axis=1)


arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#spliting

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Random Numbers in NumPy

In [ ]:
from numpy import random


Generate a random integer from 0 to 100:

In [ ]:
x=random.randint(100)
x

62

Generate 100 random numbers

In [ ]:
x=random.rand(100)
x

array([0.55052048, 0.82674041, 0.67739965, 0.55790826, 0.70583443,
       0.11504447, 0.01069725, 0.78817254, 0.42937989, 0.54387797,
       0.377781  , 0.9876527 , 0.29141258, 0.53337237, 0.22454421,
       0.14367105, 0.24370104, 0.57179486, 0.35996865, 0.85168666,
       0.15172311, 0.37986439, 0.04681573, 0.80359312, 0.21538294,
       0.48549095, 0.99744301, 0.13439427, 0.04965752, 0.09341696,
       0.30975261, 0.34023734, 0.97390422, 0.25865424, 0.66922358,
       0.05430446, 0.56046064, 0.55911134, 0.81371061, 0.27069138,
       0.57436538, 0.56362785, 0.54016595, 0.60389286, 0.53710344,
       0.54719586, 0.55478541, 0.55648695, 0.19377339, 0.39307445,
       0.86352461, 0.42456936, 0.40930629, 0.80467965, 0.15145185,
       0.70496669, 0.05338529, 0.20022159, 0.27193989, 0.27238977,
       0.95444399, 0.62737403, 0.74202461, 0.70477675, 0.88066345,
       0.70398587, 0.90718739, 0.05606423, 0.16022582, 0.20056096,
       0.33902274, 0.63234223, 0.04875612, 0.01252854, 0.22536

In [ ]:
#Generate Random Array


x=random.randint(100,size=(5))
x

array([86, 15, 83, 63, 88])

In [ ]:
#Generate Random 2D Array

x=random.randint(100,size=(3,5))
x


array([[78, 96, 75, 38, 89],
       [63,  7, 82, 50, 24],
       [12, 10, 97, 87, 40]])

# Universal Functions

In [ ]:
#Add function

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z=np.add(x,y)

print(z)

[ 5  7  9 11]


In [ ]:
#how to create you own universal function

#To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.


def myadd(a,b):
  return a+b

myadd=np.frompyfunc(myadd,2,1)

print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


2: The first number represents the number of input arguments the Python function myadd takes. In this case, it means that myadd is a function that expects two inputs.

1: The second number represents the number of output values the Python function returns. In this case, 1 means that myadd will return one output.



In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])


newarr = np.add(arr1, arr2)
newarr1 = np.subtract(arr1, arr2)
newarr2 = np.multiply(arr1, arr2)
newarr3 = np.divide(arr1, arr2)
newarr4= np.sum([arr1,arr2])

print(newarr)
print(newarr1)
print(newarr2)
print(newarr3)
print(newarr4)

[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
210


In [ ]:
#absolute

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.



In [ ]:
arr = np.trunc([-3.1666, 3.6667])

print(arr)

arr1 = np.fix([-3.1666, 3.6667])

print(arr1)

[-3.  3.]
[-3.  3.]


In [ ]:
#Round off 3.1666 to 2 decimal places:

arr = np.around(3.1666, 2)

print(arr)

3.17


Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [ ]:
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


Products
To find the product of the elements in an array, use the prod() function.

np.array([1, 2, 3, 4])

Returns: 24 because 1 * 2 * 3 *4 = 24

In [ ]:
arr=np.array([1,2,3,4])
newarr=np.prod(arr)
newarr

24

Cummulative Product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [ ]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


Differences
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.



In [ ]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [ ]:
np.min(arr)

5

In [ ]:
np.max(arr)

25

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

result = np.hstack((a, b))
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
