In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_excel("/content/Bike_Sales_Outlier_Lab.xlsx")
df

Sales_Order #       Date  Day     Month  Year  Customer_Age  \
0          261696 2021-12-01    1  December  2021            39   
1          261695 2021-12-01    1  December  2021            44   
2          261697 2021-12-02    2  December  2021            37   
3          261698 2021-12-02    2  December  2021            31   
4          261699 2021-12-03    3  December  2021            37   
..            ...        ...  ...       ...   ...           ...   
83         261778 2021-12-22   22  December  2021            41   
84         261779 2021-12-23   23  December  2021            30   
85         261780 2021-12-23   23  December  2021            31   
86         261781 2021-12-23   23  December  2021            35   
87         261782 2021-12-24   24  December  2021            38   

               Age_Group Customer_Gender         Country             State  \
0         Adults (35-64)               F   United States        California   
1         Adults (35-64)               M  United Kingdom           England   
2         Adults (35-64)               M   United States        California   
3   Young Adults (25-34)               F       Australia   New South Wales   
4         Adults (35-64)               F   United States        California   
..                   ...             ...             ...               ...   
83        Adults (35-64)               M         Germany            Hessen   
84  Young Adults (25-34)               F   United States            Oregon   
85  Young Adults (25-34)               F          Canada  British Columbia   
86        Adults (35-64)               F   United States        California   
87        Adults (35-64)               M       Australia        Queensland   

   Product_Category    Sub_Category        Product_Description  \
0             Bikes  Mountain Bikes     Mountain-200 Black, 46   
1             Bikes  Mountain Bikes    Mountain-200 Silver, 42   
2             Bikes  Mountain Bikes  Mountain-400-W Silver, 46   
3             Bikes  Mountain Bikes  Mountain-400-W Silver, 42   
4             Bikes  Mountain Bikes     Mountain-200 Black, 46   
..              ...             ...                        ...   
83            Bikes  Mountain Bikes    Mountain-200 Silver, 38   
84            Bikes  Mountain Bikes    Mountain-200 Silver, 42   
85            Bikes  Mountain Bikes     Mountain-200 Black, 42   
86            Bikes  Mountain Bikes     Mountain-500 Black, 42   
87            Bikes  Mountain Bikes     Mountain-200 Black, 42   

    Order_Quantity   Unit_Cost    Unit_Price    Profit    Cost   Revenue  
0                4         1252          2295      4172    5008     9180  
1                1         1266          2320      1054    1266     2320  
2                2          420           769       698     840     1538  
3                1          420           769       349     420      769  
4                2         1252          2295      2086    2504     4590  
..             ...          ...           ...       ...     ...      ...  
83               1         1266          2320      1054    1266     2320  
84               1         1266          2320      1054    1266     2320  
85               1         1252          2295      1043    1252     2295  
86               1          295           540       245     295      540  
87               4         1252          2295      4172    5008     9180  

[88 rows x 19 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   Sales_Order #        88 non-null     int64         
 1   Date                 88 non-null     datetime64[ns]
 2   Day                  88 non-null     int64         
 3   Month                88 non-null     object        
 4   Year                 88 non-null     int64         
 5   Customer_Age         88 non-null     int64         
 6   Age_Group            88 non-null     object        
 7   Customer_Gender      88 non-null     object        
 8   Country              88 non-null     object        
 9   State                88 non-null     object        
 10  Product_Category     88 non-null     object        
 11  Sub_Category         88 non-null     object        
 12  Product_Description  88 non-null     object        
 13  Order_Quantity       88 non-null     

In [6]:
df.isnull().sum()

Sales_Order #          0
Date                   0
Day                    0
Month                  0
Year                   0
Customer_Age           0
Age_Group              0
Customer_Gender        0
Country                0
State                  0
Product_Category       0
Sub_Category           0
Product_Description    0
Order_Quantity         0
 Unit_Cost             0
 Unit_Price            0
 Profit                0
 Cost                  0
Revenue                0
dtype: int64

In [7]:
df.describe().T

count                           mean                  min  \
Sales_Order #   88.0                       261738.5             261695.0   
Date              88  2021-12-13 13:21:49.090909184  2021-12-01 00:00:00   
Day             88.0                      13.556818                  1.0   
Year            88.0                         2021.0               2021.0   
Customer_Age    88.0                      34.170455                 17.0   
Order_Quantity  88.0                       2.238636                  1.0   
 Unit_Cost      88.0                    1064.204545                295.0   
 Unit_Price     88.0                    1945.659091                540.0   
 Profit         88.0                    1858.045455                245.0   
 Cost           88.0                    2390.727273                295.0   
Revenue         88.0                    4368.545455                540.0   

                                25%                  50%                  75%  \
Sales_Order #             261716.75             261738.5            261760.25   
Date            2021-12-08 18:00:00  2021-12-13 12:00:00  2021-12-19 00:00:00   
Day                            8.75                 13.5                 19.0   
Year                         2021.0               2021.0               2021.0   
Customer_Age                  29.75                 35.0                 38.0   
Order_Quantity                  1.0                  2.0                 3.25   
 Unit_Cost                   1044.0               1252.0               1266.0   
 Unit_Price                  1913.5               2295.0               2320.0   
 Profit                      1043.0               1054.0              2997.75   
 Cost                        1252.0               1266.0               3756.0   
Revenue                      2295.0               2320.0               6885.0   

                                max          std  
Sales_Order #              261782.0    25.547342  
Date            2021-12-24 00:00:00          NaN  
Day                            24.0     6.356928  
Year                         2021.0          0.0  
Customer_Age                   63.0     8.131423  
Order_Quantity                 11.0     1.553597  
 Unit_Cost                   1912.0   428.250361  
 Unit_Price                  3400.0   776.031192  
 Profit                      5908.0  1399.697709  
 Cost                       13926.0  2117.377084  
Revenue                     25520.0  3856.531906

In [9]:
df.columns

Index(['Sales_Order #', 'Date', 'Day', 'Month', 'Year', 'Customer_Age',
       'Age_Group', 'Customer_Gender', 'Country', 'State', 'Product_Category',
       'Sub_Category', 'Product_Description', 'Order_Quantity', ' Unit_Cost ',
       ' Unit_Price ', ' Profit ', ' Cost ', 'Revenue'],
      dtype='object')

In [13]:
order_quantity=np.array(df["Order_Quantity"])
unit_cost=np.array(df[' Unit_Cost '])
unit_price=np.array(df[' Unit_Price '])

cost = np.multiply(order_quantity, unit_cost)
revenue = np.multiply(order_quantity, unit_price)
profit = revenue - cost

print("Cost:", cost)
print("Revenue:", revenue)
print("Profit:", profit)

Cost: [ 5008  1266   840   420  2504  1252  1252  1680  5008  5008  1266  1252
  1260  1252  1252  1266  1680  2532  1232  5064  2504   295  3796  1266
  2504  2504  1252   295  1912  1252  3756   840  1252   420  1266  5064
  1680  2504  1266  1266  3798   308  1252  1252  2532  1252   420  1266
  2504  2504  1266  2532   420  1266  1232  5064  3798  1260  3756  1252
  1266  5064  1180  5008  7592  5008  5008  5008   590  2504 13926  7592
  5008   885  1266  1266  3798   840  3798  3756   308  1252  1252  1266
  1266  1252   295  5008]
Revenue: [ 9180  2320  1538   769  4590  2295  2295  3076  9180  9180  2320  2295
  2307  2295  2295  2320  3076  4640  2260  9280  4590   540  6750  2320
  4590  4590  2295   540  3400  2295  6885  1538  2295   769  2320  9280
  3076  4590  2320  2320  6960   565  2295  2295  4640  2295   769  2320
  4590  4590  2320  4640   769  2320  2260  9280  6960  2307  6885  2295
  2320  9280  2160  9180 13500  9180  9180  9180  1080  4590 25520 13500
  9180  16

In [14]:
mean_profit = np.mean(profit)
std_profit = np.std(profit)

# Identify outliers
outliers = profit[(profit > mean_profit + 2 * std_profit) | (profit < mean_profit - 2 * std_profit)]
print("Outliers:", outliers)

Outliers: [ 5908 11594  5908]


In [15]:
print("Min Profit:", np.min(profit))
print("Max Profit:", np.max(profit))
print("Median Profit:", np.median(profit))
print("Mean Profit:", np.mean(profit))
print("Std Deviation:", np.std(profit))

Min Profit: 245
Max Profit: 11594
Median Profit: 1054.0
Mean Profit: 1977.8181818181818
Std Deviation: 1729.839348462048


In [16]:
cumulative_profit = np.cumsum(profit)
print("Cumulative Profit (first 10 values):", cumulative_profit[:10])

Cumulative Profit (first 10 values): [ 4172  5226  5924  6273  8359  9402 10445 11841 16013 20185]


In [17]:
# Profit margin = (Profit / Revenue) * 100
profit_margin = np.divide(profit, revenue) * 100
print("Profit Margin (%):", np.around(profit_margin, 2))

Profit Margin (%): [45.45 45.43 45.38 45.38 45.45 45.45 45.45 45.38 45.45 45.45 45.43 45.45
 45.38 45.45 45.45 45.43 45.38 45.43 45.49 45.43 45.45 45.37 43.76 45.43
 45.45 45.45 45.45 45.37 43.76 45.45 45.45 45.38 45.45 45.38 45.43 45.43
 45.38 45.45 45.43 45.43 45.43 45.49 45.45 45.45 45.43 45.45 45.38 45.43
 45.45 45.45 45.43 45.43 45.38 45.43 45.49 45.43 45.43 45.38 45.45 45.45
 45.43 45.43 45.37 45.45 43.76 45.45 45.45 45.45 45.37 45.45 45.43 43.76
 45.45 45.37 45.43 45.43 45.43 45.38 45.43 45.45 45.49 45.45 45.45 45.43
 45.43 45.45 45.37 45.45]


In [19]:
# Reshape profits into 4 weeks (approximate)
weekly_profits = profit[:28].reshape(4, 7)  # First 28 entries as 4 weeks
print("Weekly Profits:\n", weekly_profits)

Weekly Profits:
 [[4172 1054  698  349 2086 1043 1043]
 [1396 4172 4172 1054 1043 1047 1043]
 [1043 1054 1396 2108 1028 4216 2086]
 [ 245 2954 1054 2086 2086 1043  245]]
